### ISSUE TITLE
Support Cloud API

### ISSUE THREAD

**Issue by tacotexmex** [rautars/happy_weather#1]
By using `player:set_clouds` you can control the cloud setting: density, color, ambience, height, thickness and speed, many of which will increase weather immersion (instead of just removing the clouds and changing the sky color).

**Comment by rautars** [comment]
Thanks for letting me know I will check new clouds API capabilities

**Comment by rautars** [comment]
Skylayer now supports clouds transitions, weather_pack and happy_weather samples was updated accordingly.

**Comment by tacotexmex** [comment]
That was fast! Thanks!
